[pytest]
testpaths = tests
addopts = -ra
filterwarnings =
    error::ResourceWarning
    ignore:This process .* is multi-threaded, use of fork\(\) may lead to deadlocks in the child\.:DeprecationWarning
